# Generated by Django 4.2.2 on 2023-10-23 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agama', models.CharField(max_length=256, verbose_name='Agama')),
                ('ket', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=10)),
                ('ket', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Biodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nip', models.CharField(max_length=8)),
                ('alamat', models.TextField()),
                ('mapel', models.CharField(max_length=50)),
                ('agama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biodata.agama')),
                ('jk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biodata.jenis')),
            ],
        ),
    ]
