# Generated by Django 4.2.1 on 2023-10-24 03:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
        ('presensi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presensi',
            name='status',
            field=models.CharField(default='Masuk', max_length=10),
        ),
        migrations.CreateModel(
            name='PresensiPulang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pulang', max_length=10)),
                ('tgl', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('nama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biodata.biodata')),
            ],
        ),
    ]
